# Filled manually for setting the specs desired in the results analysis

# Correction factor for atmospheric conditions.
sae_j1349: True # True/False

# Units
power_unit: 'cv' # cv/kW
torque_unit: 'nm' # nm/kgfm

# Advanced settings
smoothing_factor: 1000